### ISSUE TITLE
CartEditField - Quantity field formatting to locale but data not supported when saving

### ISSUE THREAD

**Issue by StephenHonor** [silvershop/silvershop-core#386] opened 2015-11-03 09:04 UTC
When you enter a large number in the Quantity (NumericField) field. It formats the number to the current locale with commas.

However, the data supplied by the NumericField is not supported within the CartForm class when saving so reverts back to 0 when saving.

I know of 2 options currently and they are:

1. Change the NumericField to TextField
2. Try to get the data to be pulled from the NumericField's dataValue method. This has the adaquate Zend Locale functionality which converts the value back into a number.

**Comment by markguinn** [comment] 2015-11-03 12:49
I'd be more comfortable with the second option. Can you see an easy way to make that happen?

**Comment by bummzack** [comment] 2016-06-06 08:38
This is a framework issue and should be resolved by now. @StephenHonor Do you still run into these issues with SilverStripe 3.3 or 3.2.4?

**Comment by StephenHonor** [comment] 2016-06-06 08:44
From last checking when I looked into the way it works. I believe the NumericField works fine in core. However, the Quantity field seems to override some functionality which causes it not to take into account the locale when spitting back the number itself.

**Comment by bummzack** [comment] 2016-06-06 08:48
@StephenHonor Thanks for the fast reply. I think it might be the same issue as this one: https://github.com/silverstripe/silverstripe-framework/issues/4550. The solution would be to not use a "numeric" input here. I'll look into it.

**Comment by StephenHonor** [comment] 2016-06-06 08:52
That is one a

**Comment by bummzack** [comment] 2016-06-06 08:54
I think the issue is still unfixed. Reopened.

**Comment by bummzack** [comment] 2016-06-06 09:54
A possible fix could be:
```php
//update quantities
if (isset($fields['Quantity']) && $quantity = Convert::raw2sql($fields['Quantity'])) {
    $f = NumericField::create('Temp');
    $f->setValue($quantity);
    $item->Quantity = $f->dataValue();
}
```
Which would ensure the number runs through the Zend locale formatter.

Currently, the field is rendered as an HTML5 numeric-input (eg. an input field with a stepper). This field-type doesn't support locale formatted numbers though…
This means that people weren't able to enter locale formatted numbers there, unless they changed templates to use another input-field.

I'm leaning towards the following solution: Run quantity numbers through the `NumericField`, so that people can change to a locale-formatted input field without breaking the cart. Leave the numeric-field as a HTML5 input, because the numeric-stepper is convenient and won't break existing setups?

@markguinn thoughts?

**Comment by bummzack** [comment] 2016-06-06 11:43
I was wrong in my assumption about the HTML5 input… The numeric field can render a number like this `1,000` which isn't a valid value for the HTML5 number input field (results in a blank field).

**Closed** 2016-06-30 19:03 UTC
