### ISSUE TITLE
Order Items with zero quantity

### ISSUE THREAD

**Issue by vixen1975** [silvershop/silvershop-core#568] opened 2016-12-20 02:45 UTC
This is really a question, not an issue, but I was curious if anyone can shed any light on how an order can come through with some items having zero quantity.

When I have removed or updated an item to have 0 in my cart, I can see it disappear from the OrderItems table, but my site has an instance where an order has come through with 4 different products, 2 of which are fine, 2 have zero quantity.

What I can guess from looking at the different tables is that the person originally added things to their cart on the 28/11 and did not proceed with the order, came back yesterday (19/12) and placed an order. The two items from the 28th are the ones showing 0. One of them was no longer available so that would make sense, but the other one is available.

Does anyone know why an item with zero quantity would still show on the order in the cms?

Thanks

**Comment by bummzack** [comment] 2016-12-20 08:08
Can you clarify the steps to reproduce this issue? Is it:

1. Put items in cart (as customer)
2. Make items no longer available (as admin)
3. Set quantity of the items in cart to 0 (as customer)

Also, what version of shop are you using?

**Comment by bummzack** [comment] 2017-10-24 08:19
Closing due to missing feedback.

**Closed by bummzack** 2017-10-24 08:19 UTC
